//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSIXBizTalkBuildAndDeploy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSIXBizTalkBuildAndDeploy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot; ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot;&gt;	
        ///	&lt;Import Project=&quot;@ApplicationName@.Custom.targets&quot;/&gt;
        ///	&lt;Import Project=&quot;@ApplicationName@.targets&quot;/&gt;
        ///	&lt;Import Project=&quot;@ApplicationName@.Rules.targets&quot;/&gt;
        ///				
        ///	&lt;Target Name=&quot;Build&quot;&gt;
        ///
        ///		&lt;!-- Set the new version --&gt;
        ///		&lt;CallTarget Targets=&quot;AssemblyVersioning&quot;/&gt;
        ///
        ///		&lt;CallTarget Targets=&quot;CleanUp&quot;/&gt;
        ///		&lt;CallTarget Targets=&quot;Setup&quot;/&gt;
        ///
        ///		&lt;!-- Create the R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App_Build {
            get {
                return ResourceManager.GetString("App_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo Executing script
        ///@echo
        ///&quot;%systemroot%\Microsoft.NET\Framework\v4.0.30319\msbuild.exe&quot; @ApplicationName@.Build.proj /p:ConfigurationName=Debug,Platform=&quot;Any CPU&quot;,DeploymentMode=Development,IncludeTests=True,GenerateBindings=@GenerateBindings@
        ///@echo off
        ///pause.
        /// </summary>
        internal static string App_Build_Debug {
            get {
                return ResourceManager.GetString("App_Build_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo Executing script
        ///@echo
        ///&quot;%systemroot%\Microsoft.NET\Framework\v4.0.30319\msbuild.exe&quot; @ApplicationName@.Build.proj /p:ConfigurationName=Release,Platform=&quot;Any CPU&quot;,DeploymentMode=Deployment,IncludeTests=False,GenerateBindings=@GenerateBindings@
        ///@echo off
        ///pause.
        /// </summary>
        internal static string App_Build_Release {
            get {
                return ResourceManager.GetString("App_Build_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///	&lt;PropertyGroup&gt;
        ///
        ///		&lt;!--
        ///		&lt;BizTalkDatabaseServerName&gt;.&lt;/BizTalkDatabaseServerName&gt;
        ///		&lt;BizTalkManagementDatabaseName&gt;BizTalkMgmtDB&lt;/BizTalkManagementDatabaseName&gt;
        ///		&lt;PipelineComponentsFolderPath&gt;C:\Program Files (x86)\Microsoft BizTalk Server 2010\Pipeline Components&lt;/PipelineComponentsFolderPath&gt;
        ///		--&gt;
        ///&lt;!-- @CustomProperties@ --&gt;
        ///
        ///		&lt;BizTalkManagementDatabaseConnectionString&gt;server=$(BizT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App_Custom_Properties {
            get {
                return ResourceManager.GetString("App_Custom_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///	&lt;Import Project=&quot;@ApplicationName@.properties&quot;/&gt;	
        ///	&lt;Import Project=&quot;@ApplicationName@.Custom.properties&quot;/&gt;
        ///
        ///	&lt;Target Name=&quot;BeforeCleanUp&quot;&gt;
        ///		&lt;!-- Add Custom Setup Here --&gt;
        ///	&lt;/Target&gt;
        ///	
        ///	&lt;Target Name=&quot;AfterCleanUp&quot;&gt;
        ///		&lt;!-- Add Custom Setup Here --&gt;
        ///	&lt;/Target&gt;
        ///	
        ///	&lt;Target Name=&quot;BeforeSetup&quot;&gt;
        ///		&lt;!-- Add Custom Setup Here --&gt;
        ///	&lt;/Target&gt;
        ///	
        ///	&lt;Target Name=&quot;AfterSetup&quot;&gt;
        ///		&lt;!-- Add Custom Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App_Custom_targets {
            get {
                return ResourceManager.GetString("App_Custom_targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo Executing script
        ///@echo
        ///&quot;%systemroot%\Microsoft.NET\Framework\v4.0.30319\msbuild.exe&quot; @ApplicationName@.custom.targets /t:BeforeDeployment /p:GenerateBindings=True
        ///@echo off
        ///pause.
        /// </summary>
        internal static string App_GenerateBindings {
            get {
                return ResourceManager.GetString("App_GenerateBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///	&lt;PropertyGroup&gt;
        ///		&lt;SourceCodeRootFolder&gt;@SourceCodeRootFolder@&lt;/SourceCodeRootFolder&gt;
        ///		&lt;BuildGeneratorTasksPath&gt;@BuildGeneratorTasksPath@&lt;/BuildGeneratorTasksPath&gt;		
        ///	&lt;/PropertyGroup&gt;
        ///		
        ///	&lt;Import Project=&quot;$(BuildGeneratorTasksPath)\ExtensionPack\4.0\MSBuild.ExtensionPack.tasks&quot;/&gt;
        ///	&lt;Import Project=&quot;$(BuildGeneratorTasksPath)\BizTalk Build Generator\Resources\BizTalk.BuildGenerator.Build\BizT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App_properties {
            get {
                return ResourceManager.GetString("App_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo Executing script
        ///@echo
        ///&quot;%systemroot%\Microsoft.NET\Framework\v4.0.30319\msbuild.exe&quot; @ApplicationName@.Build.proj /p:ConfigurationName=Debug,Platform=&quot;Any CPU&quot;,DeploymentMode=Development,IncludeTests=False,GenerateBindings=False
        ///@echo off
        ///pause.
        /// </summary>
        internal static string App_QuickBuild_Debug {
            get {
                return ResourceManager.GetString("App_QuickBuild_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo Executing script
        ///@echo
        ///&quot;%systemroot%\Microsoft.NET\Framework\v4.0.30319\msbuild.exe&quot; @ApplicationName@.targets /t:RemoveFromGac
        ///@echo off
        ///pause.
        /// </summary>
        internal static string App_RemoveFromGac {
            get {
                return ResourceManager.GetString("App_RemoveFromGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///
        ///	&lt;Target Name=&quot;RemoveRules&quot;&gt;
        ///&lt;!-- @RemovePoliciesCommand@ --&gt;
        ///&lt;!-- @RemoveVocabulariesCommand@ --&gt;
        ///	&lt;/Target&gt;
        ///	
        ///	&lt;Target Name=&quot;DeployRules&quot;&gt;
        ///&lt;!-- @DeployVocabulariesCommand@ --&gt;
        ///&lt;!-- @DeployPoliciesCommand@ --&gt;
        ///	&lt;/Target&gt;
        ///	
        ///&lt;/Project&gt;
        ///.
        /// </summary>
        internal static string App_Rules_targets {
            get {
                return ResourceManager.GetString("App_Rules_targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;ProgramFiles32&gt;$(MSBuildProgramFiles32)&lt;/ProgramFiles32&gt;
        ///		&lt;ProgramFiles32 Condition=&quot; &apos;&apos; == &apos;$(ProgramFiles32)&apos;&quot;&gt;$(ProgramFiles%28x86%29)&lt;/ProgramFiles32&gt;
        ///		&lt;ProgramFiles32 Condition=&quot; &apos;&apos; == &apos;$(ProgramFiles32)&apos;&quot;&gt;$(ProgramFiles)&lt;/ProgramFiles32&gt;
        ///		&lt;GacUtilPath&gt;$(ProgramFiles32)\Microsoft SDKs\Windows\v8.0A\Bin\NETFX 4.0 Tools\&lt;/GacUtilPath&gt;
        ///	&lt;/PropertyGroup&gt;
        ///	&lt;Target Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App_targets {
            get {
                return ResourceManager.GetString("App_targets", resourceCulture);
            }
        }
    }
}
